# Generated by Django 2.0.4 on 2018-05-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='amt',
            new_name='amount',
        ),
    ]
